[package]
name = "policy-guest"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
policy-core = { path = "../../crates/policy-core" }
policy-types = { path = "../../crates/policy-types" }
policy-wire = { path = "../../crates/policy-wire" }
workloads = { path = "../../crates/workloads" }

[target.'cfg(target_os = "hermit")'.dependencies]
hermit = { path = "../../vendor/hermit-rs/hermit", default-features = false, features = [
    "acpi",
    "ai-policy",
    "fsgsbase",
    "kernel-stack",
    "pci",
    "pci-ids",
    "tcp",
    "virtio-net",
] }
